### ISSUE TITLE
add option to output IRI of class in addition to annotations

### ISSUE THREAD

**Issue by hoganwr** [owl2tl/owl2tl#2]
It would be extremely valuable to have the class IRI as a column of output, in addition to the annotations.

**Comment by utecht** [comment]
I completely agree I think a checkbox or toggle would work great. I'll add
it whenever I can find a spare few minutes.

**Comment by utecht** [comment]
Added a checkbox on the main page that should fix this.  No old URLs should break but new ones generated can have the "show uri" option.
